name: bytequest
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Native Splash Screen
  flutter_native_splash: ^2.4.0

  # Good Practices
  flutter_lints: ^3.0.0

  # Changing App Icon
  icons_launcher: ^2.1.7

  # HTTP requests
  http: ^1.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
